### ISSUE TITLE
Can not delete records

### ISSUE THREAD

**Issue by maxgronlund** [Troush/turbolinks_phoenix#1]
Thanks for a great post/ and example. This should be integrated to Phoenix in the future

Here is the issue 👍 
You have to reload a page to be able to delete a record
Go to http://localhost:4000/
Then click on the link at the bottom of the page 'Users'
Then rename the first user to TestUser 1
From the Show user page click on the link at the bottom o the page "back"
Then click "Delete" to the right of TestUser 1. nothing will happen unless the page is reloaded

**Comment by Troush** [comment]
Hey, @maxgronlund. Thank you for feedback.
I created PR to fix this issue globally here https://github.com/phoenixframework/phoenix_html/pull/77
Until PR is merged you can use this verison of phoenix_html.js https://github.com/Troush/phoenix_html/blob/event-delegate-js/priv/static/phoenix_html.js

**Comment by maxgronlund** [comment]
Solved a great problem. You rocks. I have used another plugin 'turboboost' for submitting of forms. Do you have any experiences with that
https://github.com/waymondo/turboboost
