### ISSUE TITLE
channels not working with turbolinks

### ISSUE THREAD

**Issue by maxgronlund** [Troush/turbolinks_phoenix#2]
When I navigate to a page where a channel inject content. 
Then I have to reload the page for channels to work.

socket.js do not load untill I reload the page

**Comment by Troush** [comment]
I will return to this issue on weekend.

As I see know, you need to connect to socket after `turbolinks:load` event? Do you do this?

**Comment by maxgronlund** [comment]
As it stands the example don't work.
I'm adding the PR
https://github.com/Troush/phoenix_html/blob/event-delegate-js/priv/static/phoenix_html.js 
But for some reason nothing happens.
It worked for a while. I'm not sure what I'm doing wrong

**Comment by maxgronlund** [comment]
Another thing.
Inside web/templates/layout/app.html.eex
The app.js file is loaded in the body. should'n that move to the head?
