### ISSUE TITLE
There has to be a way to initiate scripts on page load

### ISSUE THREAD

**Issue by maxgronlund** [Troush/turbolinks_phoenix#3]
I used to do something like this in ROR (coffee script)
ready = ->
  alert('Chunky Beacon')

$(document).ready(ready)
$(document).on('page:load', ready)

Aparently that's not working in Phoenix.

**Comment by Troush** [comment]
You need to use 

```
document.addEventListener("turbolinks:load", function() {
  // ...
})
```

Not `page:load`
